### ISSUE TITLE
Assignment1 branch vs assignment1 branch

### ISSUE THREAD

**Issue by TwFlem** [CEN3031-spr16/UF-Directory-App-Assignment#14]
It appears that the assignment1 branch exists only to provide students a link to viewing the Assignment1 branch. Shouldn't our repo and whatever canvas link just point to the Assignment1 branch by default? It's confusing to to have two branches with same name but different case.

**Comment by Marcial1234** [comment]
'Forking' the repo and updating your local branch should do the trick
