### ISSUE TITLE
Test for 404 error checks that body is 'Bad gateway error'

### ISSUE THREAD

**Issue by irwincollin** [CEN3031-spr16/UF-Directory-App-Assignment#2]
Shouldn't a 404 error be "File not found" or "404 not found" while 502 is bad gateway? 

Also I didn't see it mentioned that the page should output 'Bad gateway error' elsewhere other than the test requiring it. So if may have to be added unless I'm missing something.

Affected File: server.test.js 
Line numbers: 65-66

``` javascript
        response.statusCode.should.be.exactly(404);
        body.should.be.exactly('Bad gateway error');
```

Maybe fixed

``` javascript
        response.statusCode.should.be.exactly(404);
        body.should.be.exactly('File not found');
```

**Comment by mattlemmone** [comment]
I agree with the status code mix up. Once more, you are right about the bad gateway error only being mentioned in the test file.

**Comment by HarryGogonis** [comment]
I agree, the response should be `404 Not Found`

For now just write 'Bad gateway error'. 

I'll talk to the other TAs but since the HW was already released, to avoid confusion we probably won't change the code.

**Comment by taylorjwalker** [comment]
Just wanted to chime in that this is still a problem. Perhaps it could be fixed for next semester?
